CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_title VARCHAR(150) NOT NULL,
    site_description VARCHAR(255) NOT NULL,
    owner_name VARCHAR(120) NOT NULL,
    headline VARCHAR(160) NOT NULL,
    short_bio VARCHAR(500) NOT NULL,
    full_bio TEXT,
    location VARCHAR(120),
    email VARCHAR(120),
    github_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    twitter_url VARCHAR(255),
    resume_url VARCHAR(255),
    profile_image_url VARCHAR(255),
    hero_image_url VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    summary VARCHAR(500) NOT NULL,
    content_markdown TEXT,
    cover_image_url VARCHAR(255),
    gallery_image_urls TEXT,
    live_url VARCHAR(255),
    repository_url VARCHAR(255),
    tech_stack TEXT,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    display_order INTEGER NOT NULL DEFAULT 0,
    seo_title VARCHAR(160),
    seo_description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    excerpt VARCHAR(500) NOT NULL,
    content_markdown TEXT NOT NULL,
    cover_image_url VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE,
    reading_time INTEGER NOT NULL DEFAULT 1,
    seo_title VARCHAR(160),
    seo_description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
