CREATE TABLE project_gallery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    alt_text VARCHAR(160)
);

CREATE TABLE project_tech_stack_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL
);

CREATE INDEX idx_project_gallery_items_project_position
    ON project_gallery_items(project_id, position);

CREATE INDEX idx_project_tech_stack_items_project_position
    ON project_tech_stack_items(project_id, position);

INSERT INTO project_gallery_items (project_id, position, image_url, alt_text)
SELECT
    p.id,
    gallery_item.ordinality - 1,
    gallery_item.value,
    NULL
FROM projects p
CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE
        WHEN p.gallery_image_urls IS NULL OR btrim(p.gallery_image_urls) = '' THEN '[]'::jsonb
        ELSE p.gallery_image_urls::jsonb
    END
) WITH ORDINALITY AS gallery_item(value, ordinality);

INSERT INTO project_tech_stack_items (project_id, position, name)
SELECT
    p.id,
    tech_item.ordinality - 1,
    tech_item.value
FROM projects p
CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE
        WHEN p.tech_stack IS NULL OR btrim(p.tech_stack) = '' THEN '[]'::jsonb
        ELSE p.tech_stack::jsonb
    END
) WITH ORDINALITY AS tech_item(value, ordinality);
